version: 2

sources:
  - name: retail360
    schema: retail360
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_stores
      - name: raw_sales
      - name: raw_inventory
      - name: raw_returns